### ISSUE TITLE
[Bug]:浏览器环境本地开发时可正常使用，执行yarn build后 部署到服务器页面报错

### ISSUE THREAD

**Issue by wangxiahui007** [DTStack/dt-sql-parser#282]
### Version

v4.0.0-beta.4.11

### Which SQL?

MySQL

### JavaScript/TypeScript code

```typescript
import { MySQL } from 'dt-sql-parser';

 const parser = new MySQL()

 const validParser = parser.validate(‘select * from test’)
```

### What happened?

index-a5bda2fb.js:7065 TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at requireSimulatorState (index-2c648bdb.js:1184:472)
    at requireParserATNSimulator (index-2c648bdb.js:1199:1162)
    at requireATNDeserializer (index-2c648bdb.js:1231:1155)
    at requireParser (index-2c648bdb.js:1190:934)
    at requireTrees (index-2c648bdb.js:1090:603)
    at requireRuleContext (index-2c648bdb.js:1093:544)
    at requireParserRuleContext (index-2c648bdb.js:1096:533)
    at index-2c648bdb.js:1099:569
m=el_conf:432 
 GET https://translate.googleapis.com/_/translate_http/_/js/k=translate_http.tr.…m=AAQ/d=1/exm=el_conf/ed=1/rs=AN8SPfqiNRRMdVNGgtvWKqGb1QNr8Cv6QQ/m=el_main net::ERR_CONNECTION_TIMED_OUT
﻿

**Comment by wangxiahui007** [comment]
vite 版本：4.2.0


![1711702303792](https://github.com/DTStack/dt-sql-parser/assets/22361025/9edc1f11-6161-4532-b562-e914bb9e29ab)
![1711704536082](https://github.com/DTStack/dt-sql-parser/assets/22361025/a806e023-3d85-4238-b15a-415aaf03b38c)

**Comment by HaydenOrz** [comment]
@wangxiahui007  尝试使用 `4.0.0-beta.4.12` 版本, 如果使用 `4.0.0-beta.4.12` 版本，仍存在问题，麻烦提供一个最小复现的demo，我刚刚尝试了一下 `4.0.0-beta.4.12` 版本是没有问题的。

你目前安装的 `4.0.0-beta.4.11` 版本使用的是 antlr4ts 运行时，这个运行时确实无法在 vite 中正常工作。

**Comment by wangxiahui007** [comment]
升级到4.0.0-beta.4.12版本后问题已解决，非常感谢
